### PR TITLE
Add required duplex option to RequestInit

### PR DESCRIPTION
**Pull request by Benzolio**
See also nodejs/node#46221 and microsoft/TypeScript-DOM-lib-generator#1483

This will prevent the following runtime error:
```
TypeError: RequestInit: duplex option is required when sending a body.
    at new Request (node:internal/deps/undici/undici:7184:19)
    at createNodeRequest (...node_modules/authey/dist/index.mjs:32:10)
```

### CODE REVIEW

**Comment by Benzolio** [comment]
This is the fix as suggested by @KararTY in Issue wobsoriano/authey#4

**Comment by Benzolio** [comment]
Well, it appears I synced a couple commits unintentionally to this request while testing, which may have stomped on some config files. I apologize for any complications that might cause.
  Anyway, I can confirm `vitest` passes, the `typecheck` does fail, but for the known reason that https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1483 mentions regarding the incomplete type in their spec which has fallen behind the actual node implementation.
  
With the single line added for `duplex: 'half'`, the build in dist works without errors when imported into an Express app and used as middleware.

**Comment by wobsoriano** [comment]
Looks like you've committed the `dist` folder and added the required lock files in gitignore. Can you update the PR to only have the `duplex` update or create a new one? Thanks!

**Comment by Benzolio** [comment]
> Looks like you've committed the `dist` folder and added the required lock files in gitignore. Can you update the PR to only have the `duplex` update or create a new one? Thanks!

Sorry about the mess of extra commits. Had some issues with vscode settings last week. I've reverted the extra commits, but now that looks even more of a mess in the history, so I did wobsoriano/authey#7 on a clean branch, if that is preferred.

**Pull request closed without merging**
